version: 2.1

orbs:
  go: circleci/go@1.3.1
  codecov: codecov/codecov@1.1.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.13

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          race: true
          coverprofile: coverage.txt
      - codecov/upload:
          file: coverage.txt


workflows:
  main:
    jobs:
      - build
